blank_issues_enabled: true
contact_links:
  - name: Nexora Launcher Matrix Support Room
    url: https://matrix.to/#/#nexora-support:matrix.org
    about: Please ask for support here before opening an issue.
